baseURL = "https://www.tangda.me/"
languageCode = "en-us"
title = "Yazhou Tang (唐亚周)"
theme = "archie"
copyright = "© Yazhou Tang"

# Code Highlight
pygmentsstyle = "solarized-light"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

pagination.pagerSize=5 # articles per page

enableemoji = true

[params]
  favicon="https://img.icons8.com/external-those-icons-lineal-color-those-icons/24/000000/external-rice-restaurant-those-icons-lineal-color-those-icons.png"
	mode="toggle" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Welcome to my personal website!"


# Social Tags

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Misc"
url = "/misc"
weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true