baseURL = "https://www.tangda.me/"
languageCode = "en-us"
title = "YazhouTang"
theme = "archie"
copyright = "© Yazhou Tang"

# Code Highlight
pygmentsstyle = "solarized-light"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# paginate=3 # articles per page

enableemoji = true

[params]
  favicon="https://img.icons8.com/external-those-icons-lineal-color-those-icons/24/000000/external-rice-restaurant-those-icons-lineal-color-those-icons.png"
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "欢迎来到我的个人网站！这里有一些记录和思考。"


# Social Tags

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:tangyazhou518@outlook.com"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/ADSWT518/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/AndrewTang518"

[[params.icon]]
name = "Zhihu"
icon = "iconfont icon-zhihu"
url = "https://www.zhihu.com/people/ADSWT518"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true